#ifdef REPORT
static NSString *objectNames[0xFF] = {
/* 0x00 */ @"floor",
/* 0x01 */ @"wall",
/* 0x02 */ @"chip",
/* 0x03 */ @"water",
/* 0x04 */ @"fire",
/* 0x05 */ @"invisible wall (won't appear)",
/* 0x06 */ @"thin wall north",
/* 0x07 */ @"thin wall west",
/* 0x08 */ @"thin wall south",
/* 0x09 */ @"thin wall east",
/* 0x0A */ @"movable block",
/* 0x0B */ @"dirt",
/* 0x0C */ @"ice",
/* 0x0D */ @"force south",
/* 0x0E */ @"clone block north",
/* 0x0F */ @"clone block west",
/* 0x10 */ @"clone block south",
/* 0x11 */ @"clone block east",
/* 0x12 */ @"force north",
/* 0x13 */ @"force east",
/* 0x14 */ @"force west",
/* 0x15 */ @"exit",
/* 0x16 */ @"blue door",
/* 0x17 */ @"red door",
/* 0x18 */ @"green door",
/* 0x19 */ @"yellow door",
/* 0x1A */ @"s-e ice",
/* 0x1B */ @"s-w ice",
/* 0x1C */ @"n-w ice",
/* 0x1D */ @"n-e ice",
/* 0x1E */ @"blue block -> floor",
/* 0x1F */ @"blue block -> wall",
/* 0x20 */ @"unused",
/* 0x21 */ @"thief",
/* 0x22 */ @"socket",
/* 0x23 */ @"green button",
/* 0x24 */ @"red button",
/* 0x25 */ @"switch block closed",
/* 0x26 */ @"switch block open",
/* 0x27 */ @"brown button",
/* 0x28 */ @"blue button",
/* 0x29 */ @"teleport",
/* 0x2A */ @"bomb",
/* 0x2B */ @"trap",
/* 0x2C */ @"invisible wall (will appear)",
/* 0x2D */ @"gravel",
/* 0x2E */ @"pass once",
/* 0x2F */ @"hint",
/* 0x30 */ @"thin wall south+east",
/* 0x31 */ @"clone machine",
/* 0x32 */ @"force random",
/* 0x33 */ @"drowning chip",
/* 0x34 */ @"burned chip",
/* 0x35 */ @"burned chip (2)",
/* 0x36 */ @"unused",
/* 0x37 */ @"unused",
/* 0x38 */ @"unused",
/* 0x39 */ @"chip in exit - end game",
/* 0x3A */ @"exit - end game",
/* 0x3B */ @"exit - end game (2)",
/* 0x3C */ @"chip swimming north",
/* 0x3D */ @"chip swimming west",
/* 0x3E */ @"chip swimming south",
/* 0x3F */ @"chip swimming east",
/* 0x40 */ @"bug (N)",
/* 0x41 */ @"bug (W)",
/* 0x42 */ @"bug (S)",
/* 0x43 */ @"bug (E)",
/* 0x44 */ @"fireball (N)",
/* 0x45 */ @"fireball (W)",
/* 0x46 */ @"fireball (S)",
/* 0x47 */ @"fireball (E)",
/* 0x48 */ @"ball (N)",
/* 0x49 */ @"ball (W)",
/* 0x4A */ @"ball (S)",
/* 0x4B */ @"ball (E)",
/* 0x4C */ @"tank (N)",
/* 0x4D */ @"tank (W)",
/* 0x4E */ @"tank (S)",
/* 0x4F */ @"tank (E)",
/* 0x50 */ @"glider (N)",
/* 0x51 */ @"glider (W)",
/* 0x52 */ @"glider (S)",
/* 0x53 */ @"glider (E)",
/* 0x54 */ @"teeth (N)",
/* 0x55 */ @"teeth (W)",
/* 0x56 */ @"teeth (S)",
/* 0x57 */ @"teeth (E)",
/* 0x58 */ @"walker (N)",
/* 0x59 */ @"walker (W)",
/* 0x5A */ @"walker (S)",
/* 0x5B */ @"walker (E)",
/* 0x5C */ @"blob (N)",
/* 0x5D */ @"blob (W)",
/* 0x5E */ @"blob (S)",
/* 0x5F */ @"blob (E)",
/* 0x60 */ @"paramecium (N)",
/* 0x61 */ @"paramecium (W)",
/* 0x62 */ @"paramecium (S)",
/* 0x63 */ @"paramecium (E)",
/* 0x64 */ @"blue key",
/* 0x65 */ @"red key",
/* 0x66 */ @"green key",
/* 0x67 */ @"yellow key",
/* 0x68 */ @"flippers",
/* 0x69 */ @"fire boots",
/* 0x6A */ @"ice skates",
/* 0x6B */ @"suction boots",
/* 0x6C */ @"chip (N)",
/* 0x6D */ @"chip (W)",
/* 0x6E */ @"chip (S)",
/* 0x6F */ @"chip (E)"
};
#endif
